[package]
name = "nasibu"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]


[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[build-dependencies]
bindgen = "0.59.2"
cbindgen = "0.20.0"
